#!/bin/bash
#
# heartsserver This shell script takes care of starting and stopping
#               heartsserver
#


# Source function library.
. /etc/rc.d/init.d/functions

# Configuration
# (this should be a separate file in a real system, keep here for now)

HEARTSSERVER="/home/luis/hearts/network-server/heartsd"
HEARTSOPTIONS="--daemon"

[ -f $HEARTSSERVER ] || exit 0

RETVAL=0
prog="heartsd"

start() {
	# Start daemon

	echo -n $"Starting $prog: "
	daemon $HEARTSSERVER $HEARTSOPTIONS
	RETVAL=$?
	echo
	return $RETVAL
}

stop() {
	# Stop daemon
	echo -n $"Shutting down $prog: "
	killproc $prog
	RETVAL=$?
	echo
	return $RETVAL
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	RETVAL=$?
	;;
  status)
	status $prog
	RETVAL=$?
	;;
  *)
	echo $"Usage: $0 {start|stop|restart|status}"
	exit 1
esac

exit $RETVAL

