#!/bin/sh
#
# heartsserver This shell script takes care of starting and stopping
#               heartsserver
#


# Configuration
# (this should be a separate file in a real system, keep here for now)

HEARTSSERVER="/home/hearts/hearts/network-server/heartsd"
HEARTSOPTIONS="--daemon"

[ -x $HEARTSSERVER ] || exit 1

RETVAL=0
prog="heartsd"
pidfile='/home/hearts/hearts.pid'
logfile='/home/hearts/heartslog'
pid=`cat $pidfile`

HEARTSOPTIONS="$HEARTSOPTIONS --logfile $logfile"
HEARTSOPTIONS="$HEARTSOPTIONS --pidfile $pidfile"

run() {
	echo $@
	$@
	return $?
} 

start() {
	# Start daemon

	echo -n "Starting $prog: "
	run $HEARTSSERVER $HEARTSOPTIONS
	RETVAL=$?
	echo $RETSTR
	return $RETVAL
}

stop() {
	# Stop daemon
	echo -n "Shutting down $prog: "
	kill $pid
	RETVAL=$?
	RETSTR="Ok"
	[ $RETVAL = "0" ] || RETSTR="Failed"
	echo $RETSTR
	return $RETVAL
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	RETVAL=$?
	;;
  status)
  	if [ -f $pidfile ]; then
		echo "$prog seems to be running (pid $pid)..."
		RETVAL=0
	else
		echo "$prog doesn't seem to be running."
		RETVAL=1
	fi
	;;
  *)
	echo $"Usage: $0 {start|stop|restart|status}"
	exit 1
esac

exit $RETVAL

